### ISSUE TITLE
4 osa kysely 5.2 IPsec?

### ISSUE THREAD

**Issue by KatanaSwing** [rage/tietoliikenteen-perusteet-2-20#20]
Tätä tehtävää ei ole mainittu 4. osan etusivun tehtävälistassa, mutta otsikon "5. Muita verkkokerroksen protokollia" mukaisella sivulla on sivun ensimmäisen tehtävän (ICMP) jälkeen näkyvissä myös toinen tehtävälaatikko, jonka tekstit eivät tule lainkaan esiin, koska se "latautuu". Tämä latautuminen ei vain missään vaiheessa toteudu, vaikka lataisi sivun uudelleen. Sivun oikeassa alareunassa olevan klikattavan sinisen pallon avaaman tehtäväpisteytyksen mukaan 4. osasta saa 12 pistettä, mutta tehtäviä ei kuitenkaan ole kuin 11 kpl 1 p/tehtävä plus tuo yksi tehtävä, joka ei jostain syystä lataudu kirjautuneelle käyttäjälle lainkaan. Voiko ko. tehtävän korjata niin, että sen pystyy myös tekemään?

**Comment by tiinaniklander** [comment]
Kiitos huomiosta ja tästä viestistä. Tehtävän linkitys  sivulle oli epäonnistunut. Pitäisi toimia hetken kuluttua.
